@baseUrl = http://localhost:5299
@contentType = application/json

### Health Check
GET {{baseUrl}}/health
Accept: {{contentType}}

### Get All Stories
GET {{baseUrl}}/api/stories
Accept: {{contentType}}

### Create a New Story
POST {{baseUrl}}/api/stories/generate
Content-Type: application/json

{
    "characterName": "Isbjørnen Theo",
    "plotId": "lost-treasure"
} 

### Get Story by ID
GET {{baseUrl}}/api/stories/00000000-0000-0000-0000-000000000000
Accept: {{contentType}}

### Get all characters
GET {{baseUrl}}/api/characters
Accept: application/json 